-- Generated by Oracle SQL Developer Data Modeler 17.3.0.261.1529
--   at:        2017-12-10 08:55:04 CET
--   site:      SQL Server 2012
--   type:      SQL Server 2012

If OBJECT_ID(N'Zadost', N'U') is not null drop table Zadost
If OBJECT_ID(N'Rezervace', N'U') is not null drop table Rezervace
If OBJECT_ID(N'Strelba', N'U') is not null drop table Strelba
If OBJECT_ID(N'Historie_zmen', N'U') is not null drop table Historie_zmen
If OBJECT_ID(N'Zbran', N'U') is not null drop table Zbran
If OBJECT_ID(N'Prostor', N'U') is not null drop table Prostor
If OBJECT_ID(N'Zakaznik', N'U') is not null drop table Zakaznik
If OBJECT_ID(N'Zamestnanec', N'U') is not null drop table Zamestnanec

GO 

CREATE TABLE Historie_zmen 
    (
     Zid INTEGER NOT NULL IDENTITY(1,1), 
     Datum_zmeny DATETIME NOT NULL , 
     idZbr INTEGER , 
     Nazev VARCHAR (30) , 
     Typ_zbrane VARCHAR (30) , 
     Raze FLOAT , 
     Rok_vyroby INTEGER , 
     Zbran_idZbr INTEGER NOT NULL 
    )
    ON "default"
GO

ALTER TABLE Historie_zmen ADD CONSTRAINT Historie_zmen_PK PRIMARY KEY CLUSTERED (Zid)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

CREATE TABLE Prostor 
    (
     idSpr INTEGER NOT NULL IDENTITY(1,1), 
     Vzdalenost FLOAT NOT NULL 
    )
    ON "default"
GO

ALTER TABLE Prostor ADD CONSTRAINT Prostor_PK PRIMARY KEY CLUSTERED (idSpr)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO


CREATE TABLE Rezervace 
    (
     idRez INTEGER NOT NULL IDENTITY(1,1), 
     datumVytvoreni DATETIME , 
     datumStrelby DATETIME , 
     Zakaznik_idZak INTEGER , 
     Prostor_idSpr INTEGER , 
     Zbran_idZbr INTEGER ,
    )
    ON "default"
GO


ALTER TABLE Rezervace ADD CONSTRAINT Rezervace_PK PRIMARY KEY CLUSTERED (idRez)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO


CREATE TABLE Strelba 
    (
     idStr INTEGER NOT NULL IDENTITY(1,1), 
     Zacatek DATETIME , 
     Konec DATETIME , 
     Zbran_idZbr INTEGER , 
     Zamestnanec_idZam INTEGER , 
     Zakaznik_idZak INTEGER , 
     Prostor_idSpr INTEGER ,
    )
    ON "default"
GO

ALTER TABLE Strelba WITH NOCHECK ADD CONSTRAINT CK_Strelba_Konec_N_Zacatek CHECK (Konec > Zacatek)

ALTER TABLE Strelba ADD CONSTRAINT Strelba_PK PRIMARY KEY CLUSTERED (idStr)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

CREATE TABLE Zakaznik 
    (
     idZak INTEGER NOT NULL IDENTITY(1,1), 
     Jmeno VARCHAR (30) NOT NULL , 
     Prijmeni VARCHAR (30) , 
     email VARCHAR (30) CHECK (email like '%@%'), 
     Datum_Narozeni DATETIME NOT NULL 
    )
    ON "default"
GO

ALTER TABLE Zakaznik ADD CONSTRAINT Zakaznik_PK PRIMARY KEY CLUSTERED (idZak)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

CREATE TABLE Zamestnanec 
    (
     idZam INTEGER NOT NULL IDENTITY(1,1), 
     Jmeno VARCHAR (30) NOT NULL , 
     Prijmeni VARCHAR (30) , 
     email VARCHAR (30) CHECK (email like '%@%'), 
     Datum_narozeni DATETIME NOT NULL 
    )
    ON "default"
GO

ALTER TABLE Zamestnanec ADD CONSTRAINT Zamestnanec_PK PRIMARY KEY CLUSTERED (idZam)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

CREATE TABLE Zbran 
    (
     idZbr INTEGER NOT NULL IDENTITY(1,1), 
     Nazev VARCHAR (30) NOT NULL , 
     Typ_zbrane VARCHAR (30) NOT NULL , 
     Raze FLOAT NOT NULL , 
     Rok_vyroby INTEGER NOT NULL 
    )
    ON "default"
GO

ALTER TABLE Zbran ADD CONSTRAINT Zbran_PK PRIMARY KEY CLUSTERED (idZbr)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

ALTER TABLE Historie_zmen 
    ADD CONSTRAINT Historie_zmen_Zbran_FK FOREIGN KEY 
    ( 
     Zbran_idZbr
    ) 
    REFERENCES Zbran 
    ( 
     idZbr 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Rezervace 
    ADD CONSTRAINT Rezervace_Prostor_FK FOREIGN KEY 
    ( 
     Prostor_idSpr
    ) 
    REFERENCES Prostor 
    ( 
     idSpr 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Rezervace 
    ADD CONSTRAINT Rezervace_Zakaznik_FK FOREIGN KEY 
    ( 
     Zakaznik_idZak
    ) 
    REFERENCES Zakaznik 
    ( 
     idZak 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Rezervace 
    ADD CONSTRAINT Rezervace_Zbran_FK FOREIGN KEY 
    ( 
     Zbran_idZbr
    ) 
    REFERENCES Zbran 
    ( 
     idZbr 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Strelba 
    ADD CONSTRAINT Strelba_Prostor_FK FOREIGN KEY 
    ( 
     Prostor_idSpr
    ) 
    REFERENCES Prostor 
    ( 
     idSpr 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Strelba 
    ADD CONSTRAINT Strelba_Zakaznik_FK FOREIGN KEY 
    ( 
     Zakaznik_idZak
    ) 
    REFERENCES Zakaznik 
    ( 
     idZak 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Strelba 
    ADD CONSTRAINT Strelba_Zamestnanec_FK FOREIGN KEY 
    ( 
     Zamestnanec_idZam
    ) 
    REFERENCES Zamestnanec 
    ( 
     idZam 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Strelba 
    ADD CONSTRAINT Strelba_Zbran_FK FOREIGN KEY 
    ( 
     Zbran_idZbr
    ) 
    REFERENCES Zbran 
    ( 
     idZbr 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

CREATE TABLE Zadost
    (
     Id INTEGER NOT NULL IDENTITY(1,1), 
     Datum_zadosti DATETIME NOT NULL ,  
     Zakaznik_idZak INTEGER NOT NULL 
    )
    ON "default"
GO

ALTER TABLE Zadost ADD CONSTRAINT ZadostPK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

ALTER TABLE Zadost 
    ADD CONSTRAINT Zadost_Zak_FK FOREIGN KEY 
    ( 
     Zakaznik_idZak
    ) 
    REFERENCES Zakaznik
    ( 
     idZak
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
